ARDUINO_DIR = /usr/share/arduino
TARGET = remote
ARDUINO_LIBS = 
MCU = atmega328p
F_CPU = 16000000
ARDUINO_PORT = /dev/ttyACM0
AVRDUDE_ARD_BAUDRATE = 115200
AVRDUDE_ARD_PROGRAMMER = arduino
OPTIMIZATION_LEVEL = 3

include /usr/share/arduino/Arduino.mk
